### ISSUE TITLE
Update schema for `donation_old` category and `displayed_notifications` feature.

### ISSUE THREAD

**Issue by radishmouse** [thunderbird/thunderbird-notifications#20]
suggestion: add something like `"$id": "https://notifications.thunderbird.net/schemas/1.0/schema.json"`

**Comment by Sancus** [comment]
I'm morphing this issue to cover:
1) Adding the "$id" as mentioned above.
2) Adding the `donation_old` category, to open donation notifications in the external browser similar to old appeals.
3) Adding the "displayed_notifications" filter so that you can exclude users that have seen a different notification id, to create mutually exclusive events.

**Comment by Sancus** [comment]
This weas fixed.
